export const LOOKS_LIST_REQUEST = 'LOOKS_LIST_REQUEST';
export const LOOKS_LIST_RECEIVED = 'LOOKS_LIST_RECEIVED';
export const LOOKS_LIST_ERROR = 'LOOKS_LIST_ERROR';
export const LOOKS_LIST_SET_PAGE = 'LOOKS_LIST_SET_PAGE';


export const LOOK_REQUEST = 'LOOK_REQUEST';
export const LOOK_RECEIVED = 'LOOK_RECEIVED';
export const LOOK_ERROR = 'LOOK_ERROR';
export const LOOK_UNLOAD = 'LOOK_UNLOAD';


export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_ID = 'USER_SET_ID';


export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

